### ISSUE TITLE
TLS support / Insecure connection on https://openpgp.org

### ISSUE THREAD

**Issue by thacoon** [OpenPGP/openpgp.github.io#5]
Using [https://openpgp.org/](https://openpgp.org/) results in an _Insecure Connection_ warning because of using github and a custom domain. The certificate is only valid for the following domains: *.github.com, github.com, *.github.io 

Maybe [gitlab](https://pages.gitlab.io/) could be used as a hoster for the static website, as there you can use a custom domain and custom ssl certificate. [Tutorial: Securing your GitLab Pages with TLS and Let's Encrypt.](https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/) This way also does not come with an extra cost.
Also SEO would benefit from using https and you could redirect users with _javascript_ to https.

**Comment by dschuermann** [comment]
Changing IPs requires some coordination effort with the domain owner, so if we would switch to GitLab, it must be a long term solution. Let's wait for https://gitlab.com/gitlab-org/gitlab-ee/issues/474 before thinking about this.

**Comment by anarcat** [comment]
FWIW, it looks like this is still pending on GitLab's side, see https://gitlab.com/gitlab-org/gitlab-ce/issues/28996 for details. Note that if you have your own X509 certificate, GitLab *already* supports configuring your own certificate, as mentioned in the original post. This is not practical for Let's Encrypt because you need to renew every three months, but could make sense with a certificate issued over longer time spans.

In the meantime, how about redirecting openpgp.org to https://openpgp.github.io/? Also note that the feature request on GitHub's side is https://github.com/isaacs/github/issues/156

**Comment by war59312** [comment]
Cloudflare an option?

How to serve a custom HTTPS domain on GitHub Pages with CloudFlare: *FREE*, secure and performant by default: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by dschuermann** [comment]
Redirecting would require some coordination effort to change IPs, which I only want to do if we have a long-term solution.

Cloudflare is currently no option because it would require the domain owner to change the DNS servers from his own to Cloudflare.

I found https://www.netlify.com . They support custom domains and TLS for jekyll builds. I will evaluate that.

**Comment by dschuermann** [comment]
Yeah, https://www.openpgp.org/ works now! I coordinated a switch to Netlify and we got a Let's Encrypt certificate.

If everything works in the next days, I will later enable HTTPS enforcing.
